"""create_professor_evidence_table

Revision ID: 6e7291ffaa57
Revises: c0a1f2d3e4b5
Create Date: 2026-05-15 21:20:58.679416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e7291ffaa57'
down_revision: Union[str, Sequence[str], None] = 'c0a1f2d3e4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('professor_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('affiliation_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_professor_evidence_lookup', 'professor_evidence', ['professor_id', 'source'], unique=False)
    op.create_index(op.f('ix_professor_evidence_professor_id'), 'professor_evidence', ['professor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professor_evidence_professor_id'), table_name='professor_evidence')
    op.drop_index('idx_professor_evidence_lookup', table_name='professor_evidence')
    op.drop_table('professor_evidence')
    # ### end Alembic commands ###
