"""Add username, career and dni to users

Revision ID: 744b703e5881
Revises: 8b48858f973a
Create Date: 2026-05-09 20:36:45.274333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744b703e5881'
down_revision: Union[str, Sequence[str], None] = '8b48858f973a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False, server_default='temp_user'))
    op.add_column('users', sa.Column('dni', sa.String(), nullable=True))
    op.add_column('users', sa.Column('career', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(None, 'users', ['dni'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'career')
    op.drop_column('users', 'dni')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
